### ISSUE TITLE
after run migrating test cases, get an error "TFS Field: step-->InvalidEmpty"

### ISSUE THREAD

**Issue by memsploitable** [premboyapati/Test-Case-Migrator-Plus#2]
I try the tool for serveral times, but only failed in action "Migrate Work Items" for "None of the test cases could be migrated", and get the error "TFS Field: step-->InvalidEmpty" in the log.

Could you please help analyze what is wrong with my tfs?
My tfs version is Azure DevOps Server version Dev17.M153.5.

Thanks.

**Comment by premboyapati** [comment]
That means you might be loading your file with an empty value for a field expecting a value. Please check your loading file.

https://learn.microsoft.com/en-us/azure/devops/organizations/settings/work/import-process/resolve-errors?view=azure-devops
