### ISSUE TITLE
Unable to add test case excel file

### ISSUE THREAD

**Issue by VijayWadi2273** [premboyapati/Test-Case-Migrator-Plus#4]
Dear Team,

We use TCM pro plus tool in our office,

With this tool some users can export the test case excels without any issue,
but some users are unable to add the test case file on TCM tool.

error screenshot attached, please help me to sort out this issue.

![TCM_Error](https://user-images.githubusercontent.com/85390279/147725698-adf18d43-a874-437c-8811-36d35fb10203.JPG)

Thanks,

**Comment by premboyapati** [comment]
This will happen only if your office is installed and the registry setting has incorrect configs to the EXCEL location. So Please open the control panel --> Programs --> Select MS Office --> Righ click - change option --> Restart your machine. Now, your app should work fine.

![image](https://github.com/premboyapati/Test-Case-Migrator-Plus/assets/2793245/40a23688-551a-46ee-8878-99f77387eb5e)
